export const teamData = [
  {
    unique: "SEMNASTI2025-A1BCD",
    name: "Dimas Aryaputra",
    email: "dimas.arya@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-A2EFG",
    name: "Rama Danu Pradipta",
    email: "rama.danu@students.example.com",
    present: false,
  },
  {
    unique: "SEMNASTI2025-A3HIJ",
    name: "Kevin Prasetyo",
    email: "kevin.pras@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-A4KLM",
    name: "Alif Nur Hidayat",
    email: "alif.hidayat@students.example.com",
    present: false,
  },
  {
    unique: "SEMNASTI2025-A5NOP",
    name: "Rizky Faizal",
    email: "rizky.faizal@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-A6QRS",
    name: "Bagas Ardiansyah",
    email: "bagas.ardi@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-A7TUV",
    name: "Yuda Permadi",
    email: "yuda.permadi@students.example.com",
    present: false,
  },
  {
    unique: "SEMNASTI2025-A8WXY",
    name: "Rafi Maulana",
    email: "rafi.maulana@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-A9ZBC",
    name: "Fikri Wahyudi",
    email: "fikri.wahyudi@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-B1DEF",
    name: "Teguh Pramudya",
    email: "teguh.pramudya@students.example.com",
    present: false,
  },
  {
    unique: "SEMNASTI2025-B2GHI",
    name: "Akbar Yusman",
    email: "akbar.yusman@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-B3JKL",
    name: "Hafiz Rahmad",
    email: "hafiz.rahmad@students.example.com",
    present: false,
  },
  {
    unique: "SEMNASTI2025-B4MNO",
    name: "Rendy Julian",
    email: "rendy.julian@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-B5PQR",
    name: "Darma Wijaya",
    email: "darma.wijaya@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-B6STU",
    name: "Jovan Surya",
    email: "jovan.surya@students.example.com",
    present: false,
  },
  {
    unique: "SEMNASTI2025-B7VWX",
    name: "Galih Fatur",
    email: "galih.fatur@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-B8YZA",
    name: "Ilham Nugraha",
    email: "ilham.nugraha@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-C1BCD",
    name: "Agung Perdana",
    email: "agung.perdana@students.example.com",
    present: false,
  },
  {
    unique: "SEMNASTI2025-C2EFG",
    name: "Devan Rasyid",
    email: "devan.rasyid@students.example.com",
    present: true,
  },
  {
    unique: "SEMNASTI2025-C3HIJ",
    name: "Farhan Aditya",
    email: "farhan.aditya@students.example.com",
    present: false,
  },
  {
    unique: "SEMNASTI2025-C4KLM",
    name: "Hilmi Ramadhan",
    email: "hilmi.ramadhan@students.example.com",
    present: true,
  },
];
